apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
  labels:
    env: web
spec:
  replicas: 1
  selector:
    matchLabels:
      env: web
  template:
    metadata:
      labels:
        env: web
    spec:
      containers:
      - name: aspnetapp
        image: santospardos/sanvalero:aspnet-mssql-web-v2
        ports:
        - containerPort: 80
